--ORDRE DES COLONNES (ID, BUDGET, PRESIDENT,PAYS-ROYAUME,PAYS,POPULATION, SUPERFICIE)
--INSERT INTO pays VALUES(1,400,'President',1, 70000,10,15, 1,1);
--INSERT INTO pays VALUES(2, 700,'President',false,'pays',13,15,1,1);

INSERT INTO culture VALUES(1, 'YAKA', 'SAKATA', 'REGAE', 'AUTRES');
INSERT INTO culture VALUES(2, 'LUBA', 'TSHILUBA', 'REGAE', 'AUTRES');
INSERT INTO culture VALUES(3, 'NGALA', 'EKONDA', 'SAMBO', 'AUTRES');
INSERT INTO culture VALUES(4, 'NE_KONGO', 'KIKONGO', 'REGAE', 'AUTRES');
INSERT INTO culture VALUES(5, 'UTI', 'SWAHILI', 'AFRO', 'AUTRES');